name = "MyFunctions"
uuid = "a9ae5fa8-794f-4e56-9c23-f47306214eec"
authors = ["johnzik <zgian04@gmail.com>"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
GLMakie = "0.11.8"
LinearAlgebra = "1.11.0"
SparseArrays = "1.11.0"
